# {{=<% %>=}}
---
apiVersion: deployment.krateo.io/v1alpha1
kind: GcpStorageBucket
metadata:
  name: <%#norm%>{{storageBucketName}}<%/norm%>
spec:
  owner: ynap
  title: <% storageBucketName %>
  description: Provision a GCP Storage Bucket in a Project
  icon: "fa-solid fa-truck-fast"
  tags:
    - gcp
    - storagebucket
    - template
    - krateo
  plugins: []
  links:
    - url: https://test.com
      title: BitBucket project
      icon: "fa-brands fa-bitbucket"
  name:
  projectId: <% projectId %>
  storageBucketName: <% storageBucketName %>
