# {{=<% %>=}}
---
apiVersion: deployment.krateo.io/v1alpha1
kind: GcpStorageBucket
metadata:
  name: <%#norm%>{{storageBucketName}}<%/norm%>
spec:
  owner: ynap
  title: <% storageBucketName %>
  description: Provision a GCP Storage Bucket in a Project
  icon: "fa-solid fa-truck-fast"
  tags:
    - gcp
    - storagebucket
    - template
    - krateo
  plugins: []
  links:
    - url: https://console.cloud.google.com/storage/browser?project=<% projectId %>
      title: Gcp Storage Bucket
      icon: "fa-solid fa-bucket"
  name:
  projectId: <% projectId %>
  storageBucketName: <% storageBucketName %>
